import type { Metadata } from "next";
import { Geist, Geist_Mono, Playfair_Display } from "next/font/google";
import "./globals.css";
import Footer from "@/component/footer";
import Header from "@/component/header";
import { CalculatorProvider } from "@/context/CalculatorContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const playfair = Playfair_Display({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-playfair'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className={`${playfair.variable} ${geistSans.variable} ${geistMono.variable} antialiased font-sans min-h-screen w-full bg-pink-50 flex flex-col`}
      >
        <CalculatorProvider>
          <Header />
          <main className="flex-grow">
            {children}
          </main>
          <Footer />
        </CalculatorProvider>
      </body>
    </html>
  );
}
