import type { Metadata } from "next";
import { Geist, Geist_Mono, Playfair_Display } from "next/font/google";
import "./globals.css";
import Footer from "@/component/footer";
import Header from "@/component/header";
import MobileHeader from "@/component/mobile-header";
import { CalculatorProvider } from "@/context/CalculatorContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const playfair = Playfair_Display({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-playfair",
});

export const metadata: Metadata = {
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className={`${playfair.variable} ${geistSans.variable} ${geistMono.variable} antialiased font-sans min-h-screen w-full bg-pink-50 flex flex-col`}
      >
        <CalculatorProvider>
          <MobileHeader />
          <Header />
          <main className="flex-grow pt-16 md:pt-0">{children}</main>
          <Footer />
        </CalculatorProvider>
      </body>
    </html>
  );
}
